# Generated by Django 4.2.23 on 2025-08-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_grupotrabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='participantes',
        ),
        migrations.AddField(
            model_name='reunion',
            name='grupo_trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='mi_aplicacion.grupotrabajo'),
            preserve_default=False,
        ),
    ]
