# Generated by Django 4.2.23 on 2025-08-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_remove_reunion_participantes_reunion_grupo_trabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervencion',
            old_name='timestamp',
            new_name='fecha_creacion',
        ),
    ]
