# Generated by Django 4.2.23 on 2025-08-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_rename_timestamp_intervencion_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='usuario',
        ),
    ]
