# Generated by Django 4.2.23 on 2025-08-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_rename_texto_comentario_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
    ]
