# Generated by Django 4.2.23 on 2025-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_rename_usuario_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='estado',
            field=models.CharField(choices=[('sin_iniciar', 'Sin iniciar'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='sin_iniciar', max_length=20),
        ),
    ]
