# Generated by Django 4.2.23 on 2025-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_reunion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reunion',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='reuniones', to='mi_aplicacion.etiqueta'),
        ),
    ]
