# Generated by Django 4.2.23 on 2025-08-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0009_documento_reunion_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/intervenciones/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mi_aplicacion.intervencion')),
            ],
        ),
    ]
