# Generated by Django 4.2.23 on 2025-08-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0010_intervenciondocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenciondocumento',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documentos/intervenciones/'),
        ),
    ]
