# Generated by Django 4.2.23 on 2025-08-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0012_proyecto_reunion_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frentes', to='mi_aplicacion.proyecto')),
            ],
            options={
                'ordering': ('proyecto', 'nombre'),
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='reunion',
            name='frente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones', to='mi_aplicacion.frente'),
        ),
    ]
