# Generated by Django 4.2.23 on 2025-08-16 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_aplicacion', '0013_frente_reunion_frente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reunion',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='reuniones_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
