# Generated by Django 4.2.23 on 2025-08-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0014_reunion_fecha_finalizacion_reunion_responsables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
    ]
