# Generated by Django 4.2.23 on 2025-08-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0015_rename_fecha_reunion_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
